import { Product } from "./types";

export const CATEGORIES: string[] = [
  "All Categories",
  "Mobiles & Wearables",
  "Electronics",
  "Computers & Gaming",
  "Home Appliances",
  "Fashion",
  "Beauty & Personal Care",
  "Grocery & Essentials",
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-pig-stress-toy",
    title: "NoiseFit Pulse 3 Bluetooth Calling Smartwatch",
    brand: "Noise",
    category: "Mobiles & Wearables",
    price: 1799,
    originalPrice: 4999,
    discountPercent: 64,
    rating: 4.4,
    reviewCount: 1842,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&auto=format&fit=crop&q=80",
    stock: 36,
    isTrending: true,
    isBestSeller: true,
    isHeroFeatured: true,
    heroBadge: "LIMITED DEAL • 64% OFF",
    heroBannerHeadline: "Flagship AMOLED Smartwatches & Calling Bands",
    heroBannerSubtitle: "Bright outdoor display, 7-day battery life, Bluetooth calling, and precision health tracking.",
    heroOfferText: "Save 64% Today",
    description: "A daily-use smartwatch with Bluetooth calling, health tracking, bright display, and multi-day battery life for work, workouts, and travel.",
    features: [
      "Bluetooth calling with built-in speaker and mic",
      "Heart rate, SpO2, sleep, and activity tracking",
      "Bright color display with custom watch faces",
      "Water-resistant body for everyday use",
      "Up to 7 days battery life",
    ],
    specs: {
      Display: "1.85 inch TFT",
      Battery: "Up to 7 days",
      Connectivity: "Bluetooth 5.3",
      Warranty: "1 year brand warranty",
    },
    reviews: [
      {
        id: "rev-1",
        productId: "prod-pig-stress-toy",
        userName: "Aarav Sharma",
        rating: 5,
        comment: "Excellent battery life and super crisp bluetooth calls. Really impressed with TECH AI delivery speed!",
        date: "2026-08-01",
        verifiedPurchase: true,
      },
      {
        id: "rev-2",
        productId: "prod-pig-stress-toy",
        userName: "Priya Patel",
        rating: 4,
        comment: "Vibrant screen and smooth step tracking. Great value for money.",
        date: "2026-08-05",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "prod-techai-vision-pro",
    title: "Samsung Galaxy M Series 5G Smartphone",
    brand: "Samsung",
    category: "Mobiles & Wearables",
    price: 13999,
    originalPrice: 18999,
    discountPercent: 26,
    rating: 4.3,
    reviewCount: 2680,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900&auto=format&fit=crop&q=80",
    stock: 24,
    isTrending: true,
    isBestSeller: true,
    description: "A reliable 5G smartphone with a vivid display, large battery, fast processor, and practical camera setup for everyday entertainment and productivity.",
    features: [
      "5G-ready performance for fast browsing",
      "Large 6.6-inch FHD+ display for video and gaming",
      "Long-lasting 5000 mAh battery with 25W fast charging support",
      "50MP triple camera setup with Nightography",
      "Knox security protection and guaranteed OS upgrades",
    ],
    specs: {
      Display: "6.6 inch FHD+ 120Hz",
      Storage: "128 GB",
      RAM: "6 GB + RAM Plus",
      Battery: "5000 mAh",
      Processor: "Exynos 1330 Octa Core",
    },
    reviews: [
      {
        id: "rev-m1",
        productId: "prod-techai-vision-pro",
        userName: "Rahul Verma",
        rating: 5,
        comment: "Battery easily lasts 1.5 days on heavy use. Great camera in natural light!",
        date: "2026-07-28",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "prod-oneplus-nord-ce4",
    title: "OnePlus Nord CE4 5G (8GB RAM, 128GB)",
    brand: "OnePlus",
    category: "Mobiles & Wearables",
    price: 24999,
    originalPrice: 26999,
    discountPercent: 8,
    rating: 4.5,
    reviewCount: 1420,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900&auto=format&fit=crop&q=80",
    stock: 19,
    isTrending: true,
    isBestSeller: false,
    description: "Powered by Snapdragon 7 Gen 3, with 100W SUPERVOOC charging and Sony LYT-600 OIS camera system for photography enthusiasts.",
    features: [
      "Qualcomm Snapdragon 7 Gen 3 chipset",
      "100W SUPERVOOC fast charging (1-100% in 29 mins)",
      "50MP Sony LYT-600 OIS camera",
      "Fluid AMOLED 120Hz display with Aqua Touch",
      "5500 mAh battery for extreme endurance",
    ],
    specs: {
      Display: "6.7 inch AMOLED 120Hz",
      Storage: "128 GB UFS 3.1",
      RAM: "8 GB LPDDR4X",
      Charging: "100W SuperVOOC included",
    },
  },
  {
    id: "prod-boat-wave-call",
    title: "boAt Wave Call Plus AMOLED Smartwatch",
    brand: "boAt",
    category: "Mobiles & Wearables",
    price: 1999,
    originalPrice: 6999,
    discountPercent: 71,
    rating: 4.2,
    reviewCount: 3105,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=900&auto=format&fit=crop&q=80",
    stock: 45,
    isTrending: false,
    isBestSeller: true,
    description: "Ultra-slim metallic body, vivid AMOLED curved screen, bilingual voice assistance, and 700+ active sports modes.",
    features: [
      "1.83-inch HD Curved 2.5D glass display",
      "Bluetooth calling with dialpad and recent contacts save",
      "Continuous heart rate, SpO2 & stress monitor",
      "IP68 dust, sweat and splash resistant",
    ],
    specs: {
      Display: "1.83 inch HD 550 nits",
      Battery: "Up to 10 days standby",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-sony-wh1000xm5",
    title: "boAt Rockerz 450 Bluetooth On-Ear Headphones",
    brand: "boAt",
    category: "Electronics",
    price: 1499,
    originalPrice: 3990,
    discountPercent: 62,
    rating: 4.3,
    reviewCount: 4210,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&auto=format&fit=crop&q=80",
    stock: 50,
    isTrending: true,
    isBestSeller: true,
    description: "Comfortable wireless headphones with punchy bass, padded ear cushions, integrated controls, and long playback for everyday music and calls.",
    features: [
      "40mm dynamic drivers with boAt Signature Sound",
      "Up to 15 hours non-stop audio playback",
      "Padded earcups with adaptive headband",
      "Dual mode: Bluetooth wireless and 3.5mm AUX wired",
      "Voice assistant support for Siri and Google",
    ],
    specs: {
      Drivers: "40 mm",
      Playtime: "Up to 15 hours",
      Bluetooth: "Version 5.0",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-jbl-flip-6",
    title: "JBL Go 3 Portable Waterproof Bluetooth Speaker",
    brand: "JBL",
    category: "Electronics",
    price: 2999,
    originalPrice: 3999,
    discountPercent: 25,
    rating: 4.6,
    reviewCount: 3890,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&auto=format&fit=crop&q=80",
    stock: 28,
    isTrending: true,
    isBestSeller: true,
    description: "Iconic styling, rich JBL Pro Sound, IP67 waterproof and dustproof design, and rugged grab-and-go loop for adventures.",
    features: [
      "Original JBL Pro Sound with punchy bass",
      "Bold style and ultra-portable design",
      "IP67 waterproof and dustproof",
      "5 hours of playtime under single charge",
    ],
    specs: {
      Output: "4.2W RMS",
      Battery: "5 hours",
      Weight: "209 grams",
      Warranty: "1 year JBL official warranty",
    },
  },
  {
    id: "prod-oneplus-buds-pro2",
    title: "OnePlus Nord Buds 2 True Wireless Earbuds",
    brand: "OnePlus",
    category: "Electronics",
    price: 2299,
    originalPrice: 3299,
    discountPercent: 30,
    rating: 4.4,
    reviewCount: 1980,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&auto=format&fit=crop&q=80",
    stock: 32,
    isTrending: true,
    isBestSeller: false,
    description: "Active Noise Cancellation up to 25dB, BassWave bass enhancement algorithm, and 36 hours total listening time.",
    features: [
      "Up to 25dB Active Noise Cancellation",
      "12.4mm titanized dynamic audio drivers",
      "BassWave enhancement for deeper audio",
      "IP55 water and sweat resistance",
      "Fast charging: 10 mins gives 5 hours playback",
    ],
    specs: {
      Battery: "Up to 36 hours with case",
      Drivers: "12.4 mm titanized",
      ANC: "Up to 25 dB active cancellation",
    },
  },
  {
    id: "prod-mechanical-keyboard",
    title: "Redragon K552 Mechanical Gaming Keyboard",
    brand: "Redragon",
    category: "Computers & Gaming",
    price: 2499,
    originalPrice: 3999,
    discountPercent: 38,
    rating: 4.5,
    reviewCount: 1650,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add?w=900&auto=format&fit=crop&q=80",
    stock: 22,
    isTrending: true,
    isBestSeller: true,
    description: "Compact 87-key tenkeyless mechanical keyboard with tactile blue switches, rainbow backlighting, and heavy-duty metal construction.",
    features: [
      "Tactile clicky mechanical switches",
      "Compact space-saving tenkeyless layout",
      "Anti-ghosting on all 87 conflict-free keys",
      "Gold-plated high speed corrosion-free USB connector",
      "Spill-resistant industrial construction",
    ],
    specs: {
      Layout: "87 Keys TKL",
      Switches: "Custom mechanical clicky",
      Connectivity: "USB wired",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-logitech-mx3",
    title: "Logitech G102 Lightsync Optical Gaming Mouse",
    brand: "Logitech",
    category: "Computers & Gaming",
    price: 1495,
    originalPrice: 1995,
    discountPercent: 25,
    rating: 4.5,
    reviewCount: 5120,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=900&auto=format&fit=crop&q=80",
    stock: 35,
    isTrending: false,
    isBestSeller: true,
    description: "Gaming-grade 8000 DPI optical sensor, customizable RGB color wave lighting, and classic comfortable 6-button layout.",
    features: [
      "Gaming-grade 8,000 DPI optical sensor",
      "Full spectrum RGB LIGHTSYNC color wave",
      "Classic 6-button layout with metal spring tensioning",
      "Easily programmable via Logitech G HUB software",
    ],
    specs: {
      DPI: "200 - 8,000 DPI",
      Buttons: "6 programmable",
      Cable: "2.1 meters",
      Warranty: "2 year Logitech hardware warranty",
    },
  },
  {
    id: "prod-sandisk-ssd-1tb",
    title: "SanDisk 1TB Extreme Portable External SSD",
    brand: "SanDisk",
    category: "Computers & Gaming",
    price: 8499,
    originalPrice: 15500,
    discountPercent: 45,
    rating: 4.7,
    reviewCount: 920,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=900&auto=format&fit=crop&q=80",
    stock: 14,
    isTrending: true,
    isBestSeller: false,
    description: "Fast NVMe solid-state performance with up to 1050MB/s read speeds, rugged IP55 water/dust resistance, and drop protection up to 3 meters.",
    features: [
      "Fast NVMe speeds up to 1050MB/s read, 1000MB/s write",
      "Rugged design with IP55 water and dust resistance",
      "Up to 3-meter drop protection",
      "Handy carabiner loop for easy travel attachment",
    ],
    specs: {
      Capacity: "1 TB",
      Interface: "USB 3.2 Gen 2 Type-C",
      Warranty: "5 year limited warranty",
    },
  },
  {
    id: "prod-dyson-v15",
    title: "Philips Steam Iron GC1905 with Non-Stick Soleplate",
    brand: "Philips",
    category: "Home Appliances",
    price: 1699,
    originalPrice: 2295,
    discountPercent: 26,
    rating: 4.3,
    reviewCount: 3180,
    image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=900&auto=format&fit=crop&q=80",
    stock: 25,
    isTrending: false,
    isBestSeller: true,
    description: "A fast-heating 1440W steam iron with continuous steam output, spray mist function, and non-stick soleplate for quick everyday ironing.",
    features: [
      "1440W power for quick heat-up",
      "Continuous steam output up to 17 g/min",
      "Fine spray mist for stubborn creases",
      "Non-stick aluminum soleplate for smooth gliding",
      "Large 180ml water tank with easy-fill opening",
    ],
    specs: {
      Power: "1440 Watts",
      Tank: "180 ml",
      Soleplate: "Non-stick coated",
      Warranty: "2 year Philips brand warranty",
    },
  },
  {
    id: "prod-airfryer-deluxe",
    title: "Prestige Iris 750W Mixer Grinder with 4 Jars",
    brand: "Prestige",
    category: "Home Appliances",
    price: 3199,
    originalPrice: 6295,
    discountPercent: 49,
    rating: 4.2,
    reviewCount: 2890,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=900&auto=format&fit=crop&q=80",
    stock: 18,
    isTrending: true,
    isBestSeller: true,
    description: "Heavy-duty 750W copper motor mixer grinder with 3 stainless steel multipurpose jars and 1 transparent juicer jar for Indian cooking.",
    features: [
      "750 Watts powerful high-speed motor",
      "3 stainless steel jars + 1 polycarbonate juicer jar",
      "Overload protection switch for motor safety",
      "Ergonomically designed sturdy handles",
    ],
    specs: {
      Power: "750 Watts",
      Jars: "4 Jars (wet, dry, chutney, juicer)",
      Warranty: "2 year motor warranty",
    },
  },
  {
    id: "prod-havells-airfryer",
    title: "Havells Prolife Crystal 5L Digital Air Fryer",
    brand: "Havells",
    category: "Home Appliances",
    price: 5499,
    originalPrice: 11995,
    discountPercent: 54,
    rating: 4.5,
    reviewCount: 840,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=900&auto=format&fit=crop&q=80",
    stock: 12,
    isTrending: true,
    isBestSeller: false,
    description: "Rapid 360-degree air circulation technology that fries with up to 85% less oil. Features transparent viewing window and 8 digital presets.",
    features: [
      "5 Litre family size basket",
      "Transparent viewing window with internal light",
      "8 one-touch digital cooking presets",
      "Auto shut-off and overheat protection",
    ],
    specs: {
      Capacity: "5.0 Litres",
      Power: "1500 Watts",
      Temperature: "80°C - 200°C",
      Warranty: "2 year home service warranty",
    },
  },
  {
    id: "prod-adidas-f50-cleats",
    title: "Campus Everyday Running Shoes for Men",
    brand: "Campus",
    category: "Fashion",
    price: 1299,
    originalPrice: 2499,
    discountPercent: 48,
    rating: 4.2,
    reviewCount: 956,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&auto=format&fit=crop&q=80",
    stock: 42,
    isTrending: true,
    description: "Lightweight running shoes with breathable mesh upper, cushioned sole, and reliable grip for daily walking, gym sessions, and casual wear.",
    features: [
      "Breathable knitted mesh upper",
      "Soft EVA midsole cushioning",
      "Durable outsole with strong grip",
      "Lace-up fit for secure support",
      "Suitable for running and everyday use",
    ],
    specs: {
      Material: "Mesh and synthetic",
      Sole: "EVA and rubber",
      Closure: "Lace-up",
      Warranty: "30 day replacement",
    },
  },
  {
    id: "prod-omega-moonswatch-snoopy",
    title: "Titan Neo Analog Watch with Stainless Steel Strap",
    brand: "Titan",
    category: "Fashion",
    price: 3995,
    originalPrice: 5495,
    discountPercent: 27,
    rating: 4.6,
    reviewCount: 731,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=900&auto=format&fit=crop&q=80",
    stock: 18,
    isBestSeller: true,
    description: "A clean stainless steel analog watch with a versatile dial, comfortable strap, and reliable quartz movement for everyday office and casual wear.",
    features: [
      "Quartz movement for accurate timekeeping",
      "Stainless steel strap with fold-over clasp",
      "Scratch-resistant mineral glass",
      "Water resistant for daily splashes",
      "Gift-ready brand packaging",
    ],
    specs: {
      Movement: "Quartz",
      Strap: "Stainless steel",
      WaterResistance: "50m",
      Warranty: "2 year Titan manufacturer warranty",
    },
  },
  {
    id: "prod-nike-tempo-next",
    title: "Woodland Casual Leather Outdoor Boots",
    brand: "Woodland",
    category: "Fashion",
    price: 4195,
    originalPrice: 5995,
    discountPercent: 30,
    rating: 4.4,
    reviewCount: 620,
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=900&auto=format&fit=crop&q=80",
    stock: 15,
    description: "Rugged nubuck leather boots built for durability, traction, and ankle support across city streets and outdoor trails.",
    features: [
      "Genuine durable nubuck leather",
      "Deep-grooved rubber lug outsole for grip",
      "Cushioned collar for ankle protection",
      "Heavy duty brass eyelets and reinforced laces",
    ],
    specs: {
      Material: "Genuine leather",
      Sole: "Thermo-polymer rubber",
      Warranty: "90 day manufacturer warranty",
    },
  },
  {
    id: "prod-skincare-serum",
    title: "Minimalist 10% Niacinamide Face Serum (30ml)",
    brand: "Minimalist",
    category: "Beauty & Personal Care",
    price: 599,
    originalPrice: 699,
    discountPercent: 14,
    rating: 4.6,
    reviewCount: 2310,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&auto=format&fit=crop&q=80",
    stock: 40,
    isTrending: true,
    description: "Nourishing daily serum formulated with pure Niacinamide and Zinc PCA to reduce blemishes, control excess sebum, and improve skin texture.",
    features: [
      "10% Niacinamide + 1% Zinc PCA formula",
      "Fragrance-free, essential oil-free, non-comedogenic",
      "Soothes redness and strengthens skin moisture barrier",
      "Dermatologically tested for all skin types",
    ],
    specs: {
      Volume: "30 ml",
      SkinType: "All skin types",
      Origin: "India",
    },
  },
  {
    id: "prod-coffee-beans",
    title: "Tata Tea Gold Premium Long Leaf Assam Black Tea (1kg)",
    brand: "Tata Tea",
    category: "Grocery & Essentials",
    price: 549,
    originalPrice: 660,
    discountPercent: 17,
    rating: 4.5,
    reviewCount: 1560,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=900&auto=format&fit=crop&q=80",
    stock: 60,
    description: "Exquisite blend of rich Assam CTC tea gently pressed with gently rolled aromatic long tea leaves for irresistible aroma and strong taste.",
    features: [
      "Rich aroma with 15% gently rolled long leaves",
      "Authentic blend sourced from premium Assam tea gardens",
      "Airtight hygienic packaging ensuring long freshness",
    ],
    specs: {
      Weight: "1 kg",
      Form: "Loose tea",
      ShelfLife: "12 months",
    },
  },
  {
    id: "prod-iphone-15-pro-max",
    title: "Apple iPhone 15 Pro Max (256 GB) - Natural Titanium",
    brand: "Apple",
    category: "Mobiles & Wearables",
    price: 134900,
    originalPrice: 159900,
    discountPercent: 15,
    rating: 4.8,
    reviewCount: 3410,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=900&auto=format&fit=crop&q=80",
    stock: 15,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Forged in aerospace-grade titanium with the groundbreaking A17 Pro chip, customizable Action button, and the most powerful 5x telephoto camera system ever in an iPhone.",
    features: [
      "Aerospace-grade titanium design with textured matte glass back",
      "A17 Pro chip with 6-core GPU for next-gen mobile gaming",
      "Pro camera system: 48MP Main, Ultra Wide, and 5x Telephoto optical zoom",
      "Dynamic Island bubbles up alerts and Live Activities seamlessly",
      "All-day battery life with up to 29 hours video playback",
    ],
    specs: {
      Display: "6.7 inch Super Retina XDR ProMotion 120Hz",
      Storage: "256 GB NVMe",
      Chipset: "Apple A17 Pro (3nm)",
      Port: "USB-C with USB 3 speeds",
    },
  },
  {
    id: "prod-oneplus-watch-2",
    title: "OnePlus Watch 2 with Wear OS by Google (Dual Engine)",
    brand: "OnePlus",
    category: "Mobiles & Wearables",
    price: 21999,
    originalPrice: 27999,
    discountPercent: 21,
    rating: 4.6,
    reviewCount: 890,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=900&auto=format&fit=crop&q=80",
    stock: 22,
    isTrending: true,
    isBestSeller: false,
    isAiProduct: true,
    description: "Powered by Wear OS with dual-engine architecture offering up to 100 hours of battery life in Smart Mode, military-grade durability, and sapphire crystal glass.",
    features: [
      "Dual-Engine Architecture: Snapdragon W5 + BES2700 chips",
      "Up to 100 hours battery life in full Smart Mode",
      "Wear OS by Google with Google Wallet & Google Maps",
      "Sapphire crystal face with stainless steel chassis",
    ],
    specs: {
      Display: "1.43 inch AMOLED 1000 nits",
      Battery: "500 mAh (100 hours)",
      OS: "Wear OS 4 + RTOS",
      Durability: "MIL-STD-810H & 5ATM water resistance",
    },
  },
  {
    id: "prod-pixel-8a",
    title: "Google Pixel 8a 5G (Bay Blue, 128 GB)",
    brand: "Google",
    category: "Mobiles & Wearables",
    price: 43999,
    originalPrice: 52999,
    discountPercent: 17,
    rating: 4.5,
    reviewCount: 1120,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900&auto=format&fit=crop&q=80",
    stock: 18,
    isTrending: true,
    isBestSeller: false,
    isAiProduct: true,
    description: "Built with Google Tensor G3 and Google AI for effortless photos with Best Take and Magic Editor, 7 years of software support, and all-day battery life.",
    features: [
      "Google Tensor G3 chip with advanced generative AI features",
      "64MP dual rear camera system with Super Res Zoom",
      "Actua display up to 40% brighter with 120Hz smooth scrolling",
      "7 years of guaranteed OS, security, and Feature Drop updates",
    ],
    specs: {
      Display: "6.1 inch Actua OLED 120Hz",
      RAM: "8 GB LPDDR5x",
      Storage: "128 GB UFS 3.1",
      Camera: "64MP Main + 13MP Ultrawide",
    },
  },
  {
    id: "prod-fireboltt-invincible",
    title: "Fire-Boltt Invincible Plus 1.43\" AMOLED Display Smartwatch",
    brand: "Fire-Boltt",
    category: "Mobiles & Wearables",
    price: 3499,
    originalPrice: 10999,
    discountPercent: 68,
    rating: 4.3,
    reviewCount: 4120,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=900&auto=format&fit=crop&q=80",
    stock: 50,
    isTrending: false,
    isBestSeller: true,
    description: "High-end stainless steel bezel, true 4GB internal storage to save 100+ songs, Bluetooth calling, and TWS earbuds direct pairing.",
    features: [
      "1.43-inch 460x460 True AMOLED screen with Always-On",
      "4GB inbuilt local storage for music playback without phone",
      "Direct TWS headphone pairing for phone-free workouts",
      "300+ Sports modes with AI health coaching",
    ],
    specs: {
      Display: "1.43 inch AMOLED 460x460",
      Storage: "4 GB offline storage",
      Battery: "Up to 5 days normal use",
    },
  },
  {
    id: "prod-sony-wh1000xm5-premium",
    title: "Sony WH-1000XM5 Industry Leading ANC Wireless Headphones",
    brand: "Sony",
    category: "Electronics",
    price: 26990,
    originalPrice: 34990,
    discountPercent: 23,
    rating: 4.9,
    reviewCount: 4890,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900&auto=format&fit=crop&q=80",
    stock: 20,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Two processors controlling 8 microphones for unparalleled active noise cancellation, ultra-comfortable lightweight design, and 30 hours battery.",
    features: [
      "Integrated Processor V1 and HD Noise Cancelling Processor QN1",
      "Precision voice pickup with 4 beamforming microphones and AI noise reduction",
      "Up to 30 hours battery with quick 3-minute charge for 3 hours playback",
      "Multipoint connection seamlessly switches between two devices",
    ],
    specs: {
      Drivers: "30 mm specially engineered carbon fiber",
      Battery: "30 hours with ANC on",
      Codec: "LDAC, AAC, SBC",
      Weight: "250 grams",
    },
  },
  {
    id: "prod-marshall-emberton",
    title: "Marshall Emberton II Portable Bluetooth Speaker",
    brand: "Marshall",
    category: "Electronics",
    price: 14999,
    originalPrice: 19999,
    discountPercent: 25,
    rating: 4.7,
    reviewCount: 1650,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&auto=format&fit=crop&q=80",
    stock: 25,
    isTrending: true,
    isBestSeller: false,
    description: "True Stereophonic multi-directional sound, iconic retro brass & vinyl design, 30+ hours of portable playtime, and IP67 dust/water resistance.",
    features: [
      "True Stereophonic 360-degree multi-directional sound",
      "30+ hours of portable playback on a single charge",
      "Rugged IP67 water and dust resistant build",
      "Stack Mode to connect multiple Emberton II speakers together",
    ],
    specs: {
      Battery: "30+ hours",
      WaterResistance: "IP67",
      Bluetooth: "5.1 BLE",
      Weight: "700 grams",
    },
  },
  {
    id: "prod-apple-airpods-pro2",
    title: "Apple AirPods Pro (2nd Generation, MagSafe USB-C)",
    brand: "Apple",
    category: "Electronics",
    price: 20999,
    originalPrice: 24900,
    discountPercent: 16,
    rating: 4.8,
    reviewCount: 3870,
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=900&auto=format&fit=crop&q=80",
    stock: 30,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Re-engineered with the Apple H2 chip for up to 2x more Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio, and USB-C MagSafe Case.",
    features: [
      "Apple H2 headphone chip with computational audio",
      "Adaptive Audio dynamically blends Transparency and ANC",
      "Personalized Spatial Audio with dynamic head tracking",
      "Dust, sweat, and water resistant (IP54) earbuds and case",
    ],
    specs: {
      Battery: "Up to 6 hours (30 hours with case)",
      Chip: "Apple H2 in buds, U1 in MagSafe case",
      Charging: "USB-C, MagSafe, Apple Watch charger",
    },
  },
  {
    id: "prod-bose-qc45",
    title: "Bose QuietComfort 45 Over-Ear Noise Cancelling Headphones",
    brand: "Bose",
    category: "Electronics",
    price: 24900,
    originalPrice: 29900,
    discountPercent: 17,
    rating: 4.6,
    reviewCount: 2210,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&auto=format&fit=crop&q=80",
    stock: 14,
    isTrending: false,
    isBestSeller: false,
    description: "World-class acoustic noise cancelling with Quiet and Aware Modes, plush synthetic leather earcup comfort, and TriPort acoustic architecture.",
    features: [
      "Acoustic Noise Cancelling with Quiet & Aware modes",
      "High-fidelity audio with adjustable EQ in Bose Music app",
      "Lightweight comfort with minimal clamping force",
      "24 hours battery life per charge",
    ],
    specs: {
      Battery: "24 hours",
      Charging: "USB-C (15 mins gives 3 hours)",
      Weight: "240 grams",
    },
  },
  {
    id: "prod-asus-rog-strix-g16",
    title: "ASUS ROG Strix G16 Gaming Laptop (16\" FHD+ 165Hz, RTX 4060)",
    brand: "ASUS",
    category: "Computers & Gaming",
    price: 114990,
    originalPrice: 139990,
    discountPercent: 18,
    rating: 4.7,
    reviewCount: 780,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=900&auto=format&fit=crop&q=80",
    stock: 10,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Equipped with 13th Gen Intel Core i7-13650HX processor, NVIDIA GeForce RTX 4060 Laptop GPU, ROG Intelligent Cooling with liquid metal, and stunning 16:10 ROG Nebula display.",
    features: [
      "13th Gen Intel Core i7-13650HX 14 Cores / 20 Threads",
      "NVIDIA GeForce RTX 4060 8GB GDDR6 with MUX Switch & NVIDIA Advanced Optimus",
      "16-inch 16:10 FHD+ (1920x1200) 165Hz IPS display with 100% sRGB",
      "16GB DDR5 4800MHz RAM + 1TB PCIe 4.0 NVMe SSD",
    ],
    specs: {
      Processor: "Intel Core i7-13650HX",
      Graphics: "NVIDIA GeForce RTX 4060 8GB",
      RAM: "16 GB DDR5 (expandable to 32GB)",
      Storage: "1 TB M.2 NVMe PCIe Gen4",
      Display: "16 inch 165Hz 100% sRGB",
    },
  },
  {
    id: "prod-macbook-air-m3",
    title: "Apple MacBook Air 15.3-inch (M3 chip, 16GB Unified RAM, 512GB)",
    brand: "Apple",
    category: "Computers & Gaming",
    price: 144900,
    originalPrice: 154900,
    discountPercent: 6,
    rating: 4.9,
    reviewCount: 1490,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=900&auto=format&fit=crop&q=80",
    stock: 12,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Lean, mean, M3 machine. Incredibly thin design, Liquid Retina display, up to 18 hours of battery life, and high-performance Neural Engine for AI workflows.",
    features: [
      "Blazing-fast M3 chip with 8-core CPU and 10-core GPU",
      "Spacious 15.3-inch Liquid Retina display with 500 nits brightness",
      "Completely silent fanless design with up to 18 hours battery",
      "1080p FaceTime HD camera with 6-speaker spatial audio system",
    ],
    specs: {
      Display: "15.3 inch Liquid Retina 2880x1864",
      Processor: "Apple M3 Chip (16-core Neural Engine)",
      Memory: "16 GB Unified Memory",
      Storage: "512 GB SSD",
    },
  },
  {
    id: "prod-logitech-mx-master3s",
    title: "Logitech MX Master 3S Wireless Performance Ergonomic Mouse",
    brand: "Logitech",
    category: "Computers & Gaming",
    price: 8995,
    originalPrice: 10995,
    discountPercent: 18,
    rating: 4.8,
    reviewCount: 5120,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=900&auto=format&fit=crop&q=80",
    stock: 35,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "The remastered icon with Quiet Clicks, 8,000 DPI track-on-glass sensor, and MagSpeed electromagnetic scrolling for supreme precision.",
    features: [
      "MagSpeed Electromagnetic scrolling: 1,000 lines in 1 second",
      "8,000 DPI optical sensor tracks virtually anywhere, even on glass",
      "Quiet Clicks feel satisfying but make 90% less click noise",
      "Flow cross-computer control to work across Windows and macOS",
    ],
    specs: {
      DPI: "200 to 8000 DPI (50 DPI increments)",
      Battery: "Up to 70 days per full charge",
      Connectivity: "Bluetooth Low Energy & Logi Bolt USB",
    },
  },
  {
    id: "prod-keychron-k2",
    title: "Keychron K2 Wireless Mechanical Keyboard (RGB Hot-Swappable)",
    brand: "Keychron",
    category: "Computers & Gaming",
    price: 7499,
    originalPrice: 9499,
    discountPercent: 21,
    rating: 4.7,
    reviewCount: 1980,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add?w=900&auto=format&fit=crop&q=80",
    stock: 28,
    isTrending: false,
    isBestSeller: true,
    description: "Compact 75% layout wireless mechanical keyboard with Mac & Windows compatibility, hot-swappable Gateron G Pro switches, and vibrant RGB lighting.",
    features: [
      "75% layout retaining all essential function and arrow keys",
      "Bluetooth 5.1 connects up to 3 devices simultaneously",
      "Hot-swappable sockets to swap switches without soldering",
      "4000 mAh rechargeable battery lasting up to 240 hours",
    ],
    specs: {
      Switches: "Gateron G Pro Brown / Red",
      Backlight: "18 types of RGB effects",
      Battery: "4000 mAh Lithium-polymer",
    },
  },
  {
    id: "prod-dell-ultrasharp-27",
    title: "Dell UltraSharp 27\" 4K UHD USB-C Hub Monitor (U2723QE)",
    brand: "Dell",
    category: "Computers & Gaming",
    price: 49990,
    originalPrice: 62000,
    discountPercent: 19,
    rating: 4.8,
    reviewCount: 940,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=900&auto=format&fit=crop&q=80",
    stock: 16,
    isTrending: false,
    isBestSeller: false,
    description: "Brilliant IPS Black technology with 2000:1 contrast ratio, 98% DCI-P3 wide color coverage, and single-cable 90W USB-C hub connectivity.",
    features: [
      "27-inch 4K UHD 3840x2160 resolution with IPS Black panel",
      "90W Power Delivery USB-C hub with RJ45 Ethernet port",
      "ComfortView Plus built-in low blue light screen without color tint",
      "Full ergonomic tilt, swivel, pivot, and height adjustability",
    ],
    specs: {
      Resolution: "3840 x 2160 at 60 Hz",
      Contrast: "2000:1 (IPS Black)",
      Ports: "HDMI, DisplayPort 1.4, USB-C 90W, USB-A hub, RJ45",
    },
  },
  {
    id: "prod-dyson-v12-vacuum",
    title: "Dyson V12 Detect Slim Cordless Vacuum Cleaner",
    brand: "Dyson",
    category: "Home Appliances",
    price: 47900,
    originalPrice: 55900,
    discountPercent: 14,
    rating: 4.8,
    reviewCount: 1620,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=900&auto=format&fit=crop&q=80",
    stock: 12,
    isTrending: true,
    isBestSeller: true,
    isAiProduct: true,
    description: "Lightweight cordless vacuum with Fluffy Optic cleaner head that reveals invisible dust, piezo sensor to count microscopic particles, and single-button power control.",
    features: [
      "Illuminating cleaner head reveals dust invisible to naked eye",
      "Piezo sensor measures dust particles and auto-increases suction",
      "Up to 60 minutes of fade-free run time with click-in battery",
      "Hair screw tool picks up long hair and pet hair without tangling",
    ],
    specs: {
      Weight: "2.2 kg lightweight body",
      SuctionPower: "150 Air Watts",
      RunTime: "Up to 60 minutes",
      Filtration: "Whole-machine advanced filtration (99.99% down to 0.3 microns)",
    },
  },
  {
    id: "prod-philips-air-fryer",
    title: "Philips Digital Essential Air Fryer (4.1 Litre, Rapid Air)",
    brand: "Philips",
    category: "Home Appliances",
    price: 6999,
    originalPrice: 10995,
    discountPercent: 36,
    rating: 4.6,
    reviewCount: 5800,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=900&auto=format&fit=crop&q=80",
    stock: 35,
    isTrending: true,
    isBestSeller: true,
    description: "Cook with up to 90% less fat thanks to Rapid Air technology with unique starfish design. 7 digital presets for fries, chicken, fish, baking, and grilling.",
    features: [
      "Rapid Air Technology with starfish design for crispy, tender results",
      "Digital touch screen with 7 convenient preset cooking programs",
      "Keep Warm function keeps food at the ideal temperature for 30 minutes",
      "Dishwasher-safe removable parts with QuickClean basket",
    ],
    specs: {
      Capacity: "4.1 Litres (0.8 kg food)",
      Power: "1400 Watts",
      Presets: "7 digital one-touch presets",
    },
  },
  {
    id: "prod-morphy-microwave",
    title: "Morphy Richards 30L Convection Microwave Oven with Bake & Grill",
    brand: "Morphy Richards",
    category: "Home Appliances",
    price: 13490,
    originalPrice: 18990,
    discountPercent: 29,
    rating: 4.4,
    reviewCount: 1430,
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=900&auto=format&fit=crop&q=80",
    stock: 20,
    isTrending: false,
    isBestSeller: false,
    description: "All-in-one convection microwave with motorized rotisserie, 200 auto-cook menus, stainless steel cavity, and multistage cooking for gourmet dining.",
    features: [
      "30 Litre large capacity suitable for families of 4-6 members",
      "Motorized rotisserie for uniform tandoori roasting and grilling",
      "Stainless steel inner cavity for durable, hygienic cooking",
      "Deodorizer and steam clean function for easy maintenance",
    ],
    specs: {
      Capacity: "30 Litres",
      Cavity: "Stainless Steel",
      Power: "Convection 2200W, Microwave 900W",
    },
  },
  {
    id: "prod-aquaguard-ro",
    title: "Eureka Forbes Aquaguard Smart RO+UV+Copper Water Purifier",
    brand: "Aquaguard",
    category: "Home Appliances",
    price: 15499,
    originalPrice: 22000,
    discountPercent: 30,
    rating: 4.5,
    reviewCount: 3290,
    image: "https://images.unsplash.com/photo-1542013936693-884638332954?w=900&auto=format&fit=crop&q=80",
    stock: 22,
    isTrending: true,
    isBestSeller: true,
    description: "Active Copper Zinc Booster technology purifies water while infusing essential micronutrients. Multistage purification cleans water from any source.",
    features: [
      "RO + UV + MTDS purification removes bacteria, viruses, and heavy metals",
      "Active Copper & Zinc booster cartridge for natural immunity support",
      "Mineral Guard technology retains natural essential minerals like Calcium and Magnesium",
      "7 Litre food-grade transparent storage tank",
    ],
    specs: {
      Capacity: "7 Litres tank",
      Purification: "8 stages (RO + UV + UF + Copper)",
      TDSLevel: "Suitable for up to 2000 ppm",
    },
  },
  {
    id: "prod-nike-jordan-low",
    title: "Nike Air Jordan 1 Low Retro Classic Sneakers",
    brand: "Nike",
    category: "Fashion",
    price: 8995,
    originalPrice: 10995,
    discountPercent: 18,
    rating: 4.8,
    reviewCount: 4210,
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=900&auto=format&fit=crop&q=80",
    stock: 24,
    isTrending: true,
    isBestSeller: true,
    description: "Inspired by the 1985 original, the Air Jordan 1 Low offers a clean, classic look that's familiar yet fresh. Encapsulated Air-Sole unit provides lightweight cushioning.",
    features: [
      "Encapsulated Air-Sole unit in the heel for lightweight impact cushioning",
      "Genuine leather in the upper offers durability and a premium look",
      "Solid rubber outsole enhances traction on a variety of surfaces",
      "Stitched Wings logo on heel and iconic Jumpman on tongue",
    ],
    specs: {
      Material: "Genuine leather and textile",
      Sole: "Non-marking rubber cupsole",
      Closure: "Lace-up",
    },
  },
  {
    id: "prod-levis-denim-jacket",
    title: "Levi's Men's Trucker Denim Jacket (Classic Stonewash)",
    brand: "Levi's",
    category: "Fashion",
    price: 3999,
    originalPrice: 5999,
    discountPercent: 33,
    rating: 4.6,
    reviewCount: 1890,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=900&auto=format&fit=crop&q=80",
    stock: 30,
    isTrending: false,
    isBestSeller: true,
    description: "The original denim jacket since 1967. A blank canvas for self-expression that only gets better with time and natural wear.",
    features: [
      "Standard fit with pointed collar and buttoned placket",
      "Button-flap chest pockets and welt side pockets",
      "Side hem adjusters for tailored or relaxed fit",
      "100% Cotton durable rigid denim",
    ],
    specs: {
      Fabric: "100% Cotton non-stretch denim",
      Fit: "Standard trucker fit",
      WashCare: "Machine wash cold inside out",
    },
  },
  {
    id: "prod-fossil-grant-watch",
    title: "Fossil Grant Chronograph Dark Brown Leather Watch",
    brand: "Fossil",
    category: "Fashion",
    price: 9495,
    originalPrice: 13495,
    discountPercent: 30,
    rating: 4.7,
    reviewCount: 2750,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=900&auto=format&fit=crop&q=80",
    stock: 25,
    isTrending: false,
    isBestSeller: false,
    description: "Modeled after vintage clocks, Roman numeral markers are uniquely crafted to provide artistic balance to the sub-dials of the chronograph.",
    features: [
      "Chronograph movement with 24-hour display and stopwatch sub-dials",
      "Genuine dark brown calfskin leather strap with buckle closure",
      "Stainless steel case with durable scratch-resistant mineral crystal",
      "Water resistant to 50 meters (165 ft) for everyday splash protection",
    ],
    specs: {
      CaseSize: "44 mm",
      BandWidth: "22 mm interchangeable",
      WaterResistance: "5 ATM (50 meters)",
    },
  },
  {
    id: "prod-puma-velocity-nitro",
    title: "Puma Velocity Nitro 2 Lightweight Running Shoes",
    brand: "Puma",
    category: "Fashion",
    price: 5499,
    originalPrice: 9999,
    discountPercent: 45,
    rating: 4.5,
    reviewCount: 1670,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&auto=format&fit=crop&q=80",
    stock: 32,
    isTrending: true,
    isBestSeller: false,
    description: "An all-in-one neutral running shoe for any distance. The Velocity Nitro 2 features NITRO foam for exceptional responsiveness and featherlight cushioning.",
    features: [
      "NITRO: Advanced nitrogen-injected foam for superior responsiveness",
      "PUMAGRIP: Durable performance rubber compound for all-surface traction",
      "Plush engineered mesh upper with reflective accents for night safety",
      "TPU heel piece provides stability and locked-in feel",
    ],
    specs: {
      Weight: "257 grams",
      HeelToToeDrop: "8 mm",
      ArchSupport: "Neutral",
    },
  },
  {
    id: "prod-ordinary-hyaluronic",
    title: "The Ordinary Hyaluronic Acid 2% + B5 Hydration Serum (30ml)",
    brand: "The Ordinary",
    category: "Beauty & Personal Care",
    price: 750,
    originalPrice: 900,
    discountPercent: 17,
    rating: 4.7,
    reviewCount: 3900,
    image: "https://images.unsplash.com/photo-1608248597359-2a91176b6d51?w=900&auto=format&fit=crop&q=80",
    stock: 45,
    isTrending: true,
    isBestSeller: true,
    description: "A water-based formulation combining low, medium, and high molecular weight hyaluronic acid molecules with a next-gen HA crosspolymer for multi-depth hydration.",
    features: [
      "Multi-depth hydration targeting multiple skin layers",
      "Enhanced with Vitamin B5 to boost surface hydration and plumpness",
      "Lightweight, non-sticky gel texture that absorbs instantly",
      "Vegan, cruelty-free, and alcohol-free formula",
    ],
    specs: {
      Volume: "30 ml",
      SkinType: "Dry, Normal, Combination",
      Form: "Water-based serum",
    },
  },
  {
    id: "prod-cetaphil-cleanser",
    title: "Cetaphil Gentle Skin Cleanser for Dry to Normal Sensitive Skin (500ml)",
    brand: "Cetaphil",
    category: "Beauty & Personal Care",
    price: 899,
    originalPrice: 1150,
    discountPercent: 22,
    rating: 4.8,
    reviewCount: 6200,
    image: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=900&auto=format&fit=crop&q=80",
    stock: 60,
    isTrending: false,
    isBestSeller: true,
    description: "Creamy formula clinically proven to provide continuous hydration to protect against dryness. Formulated with dermatologist-backed blend of Niacinamide and Panthenol.",
    features: [
      "Defends against 5 signs of skin sensitivity: dryness, irritation, roughness, tightness, weakened barrier",
      "Soap-free, fragrance-free, hypoallergenic, and non-comedogenic",
      "Maintains natural skin moisture barrier while washing away dirt and makeup",
      "Recommended by dermatologists worldwide",
    ],
    specs: {
      Volume: "500 ml pump bottle",
      SkinType: "Sensitive, Dry to Normal",
      Origin: "Canada",
    },
  },
  {
    id: "prod-philips-shaver-5000",
    title: "Philips Series 5000 Wet & Dry Electric Shaver with SkinProtect",
    brand: "Philips",
    category: "Beauty & Personal Care",
    price: 5299,
    originalPrice: 7995,
    discountPercent: 34,
    rating: 4.5,
    reviewCount: 2410,
    image: "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=900&auto=format&fit=crop&q=80",
    stock: 28,
    isTrending: false,
    isBestSeller: false,
    description: "Delivers a powerful shave, cutting even more hair per stroke. Equipped with advanced SkinIQ technology, the shaver senses and adapts to your hair density for improved skin comfort.",
    features: [
      "SteelPrecision blades perform up to 90,000 cutting actions per minute",
      "Power Adapt sensor reads hair density 125 times per second",
      "360-D flexing heads follow facial contours for maximum skin contact",
      "Wet & dry use: shave comfortably dry or with foam or gel in the shower",
    ],
    specs: {
      Battery: "60 minutes cordless shaving per 1-hour charge",
      Blades: "45 high-performance self-sharpening blades",
      Cleaning: "One-touch open, fully washable",
    },
  },
  {
    id: "prod-blue-tokai-coffee",
    title: "Blue Tokai Roasted Coffee Beans - Attikan Estate (Medium Dark, 500g)",
    brand: "Blue Tokai",
    category: "Grocery & Essentials",
    price: 790,
    originalPrice: 950,
    discountPercent: 17,
    rating: 4.8,
    reviewCount: 2890,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=900&auto=format&fit=crop&q=80",
    stock: 55,
    isTrending: true,
    isBestSeller: true,
    description: "Single-origin Arabica beans from the Biligiriranga Hills. Tasting notes of dark chocolate, figs, and roasted almonds with a syrupy body.",
    features: [
      "100% Specialty Grade Arabica coffee beans freshly roasted to order",
      "Tasting notes: Dark Chocolate, Dried Figs, Roasted Almonds",
      "Medium-dark roast ideal for French Press, Espresso, South Indian Filter, and Moka Pot",
      "Degassing one-way valve pouch to preserve fresh roast aroma",
    ],
    specs: {
      Weight: "500 grams",
      RoastLevel: "Medium-Dark",
      Estate: "Attikan Estate, Karnataka",
    },
  },
  {
    id: "prod-organic-india-tulsi",
    title: "Organic India Tulsi Green Tea Loose Leaf (Tin Pack, 250g)",
    brand: "Organic India",
    category: "Grocery & Essentials",
    price: 385,
    originalPrice: 475,
    discountPercent: 19,
    rating: 4.6,
    reviewCount: 3150,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=900&auto=format&fit=crop&q=80",
    stock: 70,
    isTrending: false,
    isBestSeller: true,
    description: "Harmonious blend of holy Tulsi leaves with premium certified organic green tea. Rich in natural antioxidants to boost metabolism and relieve daily stress.",
    features: [
      "Certified 100% Organic ingredients grown by small family farmers",
      "Contains Rama, Krishna, and Vana Tulsi with natural polyphenol antioxidants",
      "Airtight reusable embossed tin canister keeps freshness intact",
      "Caffeine-conscious revitalizing herbal brew",
    ],
    specs: {
      Weight: "250 grams",
      Certification: "USDA Organic & India Organic",
      ShelfLife: "24 months",
    },
  },
  {
    id: "prod-ferrero-rocher",
    title: "Ferrero Rocher Premium Crispy Hazelnut Chocolates (Box of 24)",
    brand: "Ferrero",
    category: "Grocery & Essentials",
    price: 995,
    originalPrice: 1195,
    discountPercent: 17,
    rating: 4.9,
    reviewCount: 5410,
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=900&auto=format&fit=crop&q=80",
    stock: 45,
    isTrending: true,
    isBestSeller: true,
    description: "A whole crunchy hazelnut at the center, a delicious creamy hazelnut filling, a crisp wafer shell covered with milk chocolate and gently roasted hazelnut pieces.",
    features: [
      "Iconic golden wrapped hazelnut chocolates in a transparent luxury gift box",
      "Crafted with handpicked roasted Italian hazelnuts",
      "Perfect gourmet gift for birthdays, anniversaries, and festive celebrations",
    ],
    specs: {
      Count: "24 Pieces (300g)",
      Packaging: "Rigid transparent gift box",
      Storage: "Store in a cool dry place (18C-22C)",
    },
  },
];
