import { Product } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-pig-stress-toy",
    title: "NoiseFit Pulse 3 Bluetooth Calling Smartwatch",
    brand: "Noise",
    category: "Mobiles & Wearables",
    price: 1799,
    originalPrice: 4999,
    discountPercent: 64,
    rating: 4.4,
    reviewCount: 1842,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&auto=format&fit=crop&q=80",
    stock: 36,
    isTrending: true,
    isBestSeller: true,
    isHeroFeatured: true,
    heroBadge: "LIMITED DEAL • 64% OFF",
    heroBannerHeadline: "Flagship AMOLED Smartwatches & Calling Bands",
    heroBannerSubtitle: "Bright outdoor display, 7-day battery life, Bluetooth calling, and precision health tracking.",
    heroOfferText: "Save 64% Today",
    description: "A daily-use smartwatch with Bluetooth calling, health tracking, bright display, and multi-day battery life for work, workouts, and travel.",
    features: [
      "Bluetooth calling with built-in speaker and mic",
      "Heart rate, SpO2, sleep, and activity tracking",
      "Bright color display with custom watch faces",
      "Water-resistant body for everyday use",
      "Up to 7 days battery life",
    ],
    specs: {
      Display: "1.85 inch TFT",
      Battery: "Up to 7 days",
      Connectivity: "Bluetooth 5.3",
      Warranty: "1 year brand warranty",
    },
    reviews: [
      {
        id: "rev-1",
        productId: "prod-pig-stress-toy",
        userName: "Aarav Sharma",
        rating: 5,
        comment: "Excellent battery life and super crisp bluetooth calls. Really impressed with TECH AI delivery speed!",
        date: "2026-08-01",
        verifiedPurchase: true,
      },
      {
        id: "rev-2",
        productId: "prod-pig-stress-toy",
        userName: "Priya Patel",
        rating: 4,
        comment: "Vibrant screen and smooth step tracking. Great value for money.",
        date: "2026-08-05",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "prod-techai-vision-pro",
    title: "Samsung Galaxy M Series 5G Smartphone",
    brand: "Samsung",
    category: "Mobiles & Wearables",
    price: 13999,
    originalPrice: 18999,
    discountPercent: 26,
    rating: 4.3,
    reviewCount: 2680,
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900&auto=format&fit=crop&q=80",
    stock: 24,
    isTrending: true,
    isBestSeller: true,
    description: "A reliable 5G smartphone with a vivid display, large battery, fast processor, and practical camera setup for everyday entertainment and productivity.",
    features: [
      "5G-ready performance for fast browsing",
      "Large 6.6-inch FHD+ display for video and gaming",
      "Long-lasting 5000 mAh battery with 25W fast charging support",
      "50MP triple camera setup with Nightography",
      "Knox security protection and guaranteed OS upgrades",
    ],
    specs: {
      Display: "6.6 inch FHD+ 120Hz",
      Storage: "128 GB",
      RAM: "6 GB + RAM Plus",
      Battery: "5000 mAh",
      Processor: "Exynos 1330 Octa Core",
    },
    reviews: [
      {
        id: "rev-m1",
        productId: "prod-techai-vision-pro",
        userName: "Rahul Verma",
        rating: 5,
        comment: "Battery easily lasts 1.5 days on heavy use. Great camera in natural light!",
        date: "2026-07-28",
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: "prod-oneplus-nord-ce4",
    title: "OnePlus Nord CE4 5G (8GB RAM, 128GB)",
    brand: "OnePlus",
    category: "Mobiles & Wearables",
    price: 24999,
    originalPrice: 26999,
    discountPercent: 8,
    rating: 4.5,
    reviewCount: 1420,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900&auto=format&fit=crop&q=80",
    stock: 19,
    isTrending: true,
    isBestSeller: false,
    description: "Powered by Snapdragon 7 Gen 3, with 100W SUPERVOOC charging and Sony LYT-600 OIS camera system for photography enthusiasts.",
    features: [
      "Qualcomm Snapdragon 7 Gen 3 chipset",
      "100W SUPERVOOC fast charging (1-100% in 29 mins)",
      "50MP Sony LYT-600 OIS camera",
      "Fluid AMOLED 120Hz display with Aqua Touch",
      "5500 mAh battery for extreme endurance",
    ],
    specs: {
      Display: "6.7 inch AMOLED 120Hz",
      Storage: "128 GB UFS 3.1",
      RAM: "8 GB LPDDR4X",
      Charging: "100W SuperVOOC included",
    },
  },
  {
    id: "prod-boat-wave-call",
    title: "boAt Wave Call Plus AMOLED Smartwatch",
    brand: "boAt",
    category: "Mobiles & Wearables",
    price: 1999,
    originalPrice: 6999,
    discountPercent: 71,
    rating: 4.2,
    reviewCount: 3105,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=900&auto=format&fit=crop&q=80",
    stock: 45,
    isTrending: false,
    isBestSeller: true,
    description: "Ultra-slim metallic body, vivid AMOLED curved screen, bilingual voice assistance, and 700+ active sports modes.",
    features: [
      "1.83-inch HD Curved 2.5D glass display",
      "Bluetooth calling with dialpad and recent contacts save",
      "Continuous heart rate, SpO2 & stress monitor",
      "IP68 dust, sweat and splash resistant",
    ],
    specs: {
      Display: "1.83 inch HD 550 nits",
      Battery: "Up to 10 days standby",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-sony-wh1000xm5",
    title: "boAt Rockerz 450 Bluetooth On-Ear Headphones",
    brand: "boAt",
    category: "Electronics",
    price: 1499,
    originalPrice: 3990,
    discountPercent: 62,
    rating: 4.3,
    reviewCount: 4210,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900&auto=format&fit=crop&q=80",
    stock: 50,
    isTrending: true,
    isBestSeller: true,
    description: "Comfortable wireless headphones with punchy bass, padded ear cushions, integrated controls, and long playback for everyday music and calls.",
    features: [
      "40mm dynamic drivers with boAt Signature Sound",
      "Up to 15 hours non-stop audio playback",
      "Padded earcups with adaptive headband",
      "Dual mode: Bluetooth wireless and 3.5mm AUX wired",
      "Voice assistant support for Siri and Google",
    ],
    specs: {
      Drivers: "40 mm",
      Playtime: "Up to 15 hours",
      Bluetooth: "Version 5.0",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-jbl-flip-6",
    title: "JBL Go 3 Portable Waterproof Bluetooth Speaker",
    brand: "JBL",
    category: "Electronics",
    price: 2999,
    originalPrice: 3999,
    discountPercent: 25,
    rating: 4.6,
    reviewCount: 3890,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=900&auto=format&fit=crop&q=80",
    stock: 28,
    isTrending: true,
    isBestSeller: true,
    description: "Iconic styling, rich JBL Pro Sound, IP67 waterproof and dustproof design, and rugged grab-and-go loop for adventures.",
    features: [
      "Original JBL Pro Sound with punchy bass",
      "Bold style and ultra-portable design",
      "IP67 waterproof and dustproof",
      "5 hours of playtime under single charge",
    ],
    specs: {
      Output: "4.2W RMS",
      Battery: "5 hours",
      Weight: "209 grams",
      Warranty: "1 year JBL official warranty",
    },
  },
  {
    id: "prod-oneplus-buds-pro2",
    title: "OnePlus Nord Buds 2 True Wireless Earbuds",
    brand: "OnePlus",
    category: "Electronics",
    price: 2299,
    originalPrice: 3299,
    discountPercent: 30,
    rating: 4.4,
    reviewCount: 1980,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900&auto=format&fit=crop&q=80",
    stock: 32,
    isTrending: true,
    isBestSeller: false,
    description: "Active Noise Cancellation up to 25dB, BassWave bass enhancement algorithm, and 36 hours total listening time.",
    features: [
      "Up to 25dB Active Noise Cancellation",
      "12.4mm titanized dynamic audio drivers",
      "BassWave enhancement for deeper audio",
      "IP55 water and sweat resistance",
      "Fast charging: 10 mins gives 5 hours playback",
    ],
    specs: {
      Battery: "Up to 36 hours with case",
      Drivers: "12.4 mm titanized",
      ANC: "Up to 25 dB active cancellation",
    },
  },
  {
    id: "prod-mechanical-keyboard",
    title: "Redragon K552 Mechanical Gaming Keyboard",
    brand: "Redragon",
    category: "Computers & Gaming",
    price: 2499,
    originalPrice: 3999,
    discountPercent: 38,
    rating: 4.5,
    reviewCount: 1650,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add?w=900&auto=format&fit=crop&q=80",
    stock: 22,
    isTrending: true,
    isBestSeller: true,
    description: "Compact 87-key tenkeyless mechanical keyboard with tactile blue switches, rainbow backlighting, and heavy-duty metal construction.",
    features: [
      "Tactile clicky mechanical switches",
      "Compact space-saving tenkeyless layout",
      "Anti-ghosting on all 87 conflict-free keys",
      "Gold-plated high speed corrosion-free USB connector",
      "Spill-resistant industrial construction",
    ],
    specs: {
      Layout: "87 Keys TKL",
      Switches: "Custom mechanical clicky",
      Connectivity: "USB wired",
      Warranty: "1 year brand warranty",
    },
  },
  {
    id: "prod-logitech-mx3",
    title: "Logitech G102 Lightsync Optical Gaming Mouse",
    brand: "Logitech",
    category: "Computers & Gaming",
    price: 1495,
    originalPrice: 1995,
    discountPercent: 25,
    rating: 4.5,
    reviewCount: 5120,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=900&auto=format&fit=crop&q=80",
    stock: 35,
    isTrending: false,
    isBestSeller: true,
    description: "Gaming-grade 8000 DPI optical sensor, customizable RGB color wave lighting, and classic comfortable 6-button layout.",
    features: [
      "Gaming-grade 8,000 DPI optical sensor",
      "Full spectrum RGB LIGHTSYNC color wave",
      "Classic 6-button layout with metal spring tensioning",
      "Easily programmable via Logitech G HUB software",
    ],
    specs: {
      DPI: "200 - 8,000 DPI",
      Buttons: "6 programmable",
      Cable: "2.1 meters",
      Warranty: "2 year Logitech hardware warranty",
    },
  },
  {
    id: "prod-sandisk-ssd-1tb",
    title: "SanDisk 1TB Extreme Portable External SSD",
    brand: "SanDisk",
    category: "Computers & Gaming",
    price: 8499,
    originalPrice: 15500,
    discountPercent: 45,
    rating: 4.7,
    reviewCount: 920,
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=900&auto=format&fit=crop&q=80",
    stock: 14,
    isTrending: true,
    isBestSeller: false,
    description: "Fast NVMe solid-state performance with up to 1050MB/s read speeds, rugged IP55 water/dust resistance, and drop protection up to 3 meters.",
    features: [
      "Fast NVMe speeds up to 1050MB/s read, 1000MB/s write",
      "Rugged design with IP55 water and dust resistance",
      "Up to 3-meter drop protection",
      "Handy carabiner loop for easy travel attachment",
    ],
    specs: {
      Capacity: "1 TB",
      Interface: "USB 3.2 Gen 2 Type-C",
      Warranty: "5 year limited warranty",
    },
  },
  {
    id: "prod-dyson-v15",
    title: "Philips Steam Iron GC1905 with Non-Stick Soleplate",
    brand: "Philips",
    category: "Home Appliances",
    price: 1699,
    originalPrice: 2295,
    discountPercent: 26,
    rating: 4.3,
    reviewCount: 3180,
    image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=900&auto=format&fit=crop&q=80",
    stock: 25,
    isTrending: false,
    isBestSeller: true,
    description: "A fast-heating 1440W steam iron with continuous steam output, spray mist function, and non-stick soleplate for quick everyday ironing.",
    features: [
      "1440W power for quick heat-up",
      "Continuous steam output up to 17 g/min",
      "Fine spray mist for stubborn creases",
      "Non-stick aluminum soleplate for smooth gliding",
      "Large 180ml water tank with easy-fill opening",
    ],
    specs: {
      Power: "1440 Watts",
      Tank: "180 ml",
      Soleplate: "Non-stick coated",
      Warranty: "2 year Philips brand warranty",
    },
  },
  {
    id: "prod-airfryer-deluxe",
    title: "Prestige Iris 750W Mixer Grinder with 4 Jars",
    brand: "Prestige",
    category: "Home Appliances",
    price: 3199,
    originalPrice: 6295,
    discountPercent: 49,
    rating: 4.2,
    reviewCount: 2890,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=900&auto=format&fit=crop&q=80",
    stock: 18,
    isTrending: true,
    isBestSeller: true,
    description: "Heavy-duty 750W copper motor mixer grinder with 3 stainless steel multipurpose jars and 1 transparent juicer jar for Indian cooking.",
    features: [
      "750 Watts powerful high-speed motor",
      "3 stainless steel jars + 1 polycarbonate juicer jar",
      "Overload protection switch for motor safety",
      "Ergonomically designed sturdy handles",
    ],
    specs: {
      Power: "750 Watts",
      Jars: "4 Jars (wet, dry, chutney, juicer)",
      Warranty: "2 year motor warranty",
    },
  },
  {
    id: "prod-havells-airfryer",
    title: "Havells Prolife Crystal 5L Digital Air Fryer",
    brand: "Havells",
    category: "Home Appliances",
    price: 5499,
    originalPrice: 11995,
    discountPercent: 54,
    rating: 4.5,
    reviewCount: 840,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=900&auto=format&fit=crop&q=80",
    stock: 12,
    isTrending: true,
    isBestSeller: false,
    description: "Rapid 360-degree air circulation technology that fries with up to 85% less oil. Features transparent viewing window and 8 digital presets.",
    features: [
      "5 Litre family size basket",
      "Transparent viewing window with internal light",
      "8 one-touch digital cooking presets",
      "Auto shut-off and overheat protection",
    ],
    specs: {
      Capacity: "5.0 Litres",
      Power: "1500 Watts",
      Temperature: "80°C - 200°C",
      Warranty: "2 year home service warranty",
    },
  },
  {
    id: "prod-adidas-f50-cleats",
    title: "Campus Everyday Running Shoes for Men",
    brand: "Campus",
    category: "Fashion",
    price: 1299,
    originalPrice: 2499,
    discountPercent: 48,
    rating: 4.2,
    reviewCount: 956,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&auto=format&fit=crop&q=80",
    stock: 42,
    isTrending: true,
    description: "Lightweight running shoes with breathable mesh upper, cushioned sole, and reliable grip for daily walking, gym sessions, and casual wear.",
    features: [
      "Breathable knitted mesh upper",
      "Soft EVA midsole cushioning",
      "Durable outsole with strong grip",
      "Lace-up fit for secure support",
      "Suitable for running and everyday use",
    ],
    specs: {
      Material: "Mesh and synthetic",
      Sole: "EVA and rubber",
      Closure: "Lace-up",
      Warranty: "30 day replacement",
    },
  },
  {
    id: "prod-omega-moonswatch-snoopy",
    title: "Titan Neo Analog Watch with Stainless Steel Strap",
    brand: "Titan",
    category: "Fashion",
    price: 3995,
    originalPrice: 5495,
    discountPercent: 27,
    rating: 4.6,
    reviewCount: 731,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=900&auto=format&fit=crop&q=80",
    stock: 18,
    isBestSeller: true,
    description: "A clean stainless steel analog watch with a versatile dial, comfortable strap, and reliable quartz movement for everyday office and casual wear.",
    features: [
      "Quartz movement for accurate timekeeping",
      "Stainless steel strap with fold-over clasp",
      "Scratch-resistant mineral glass",
      "Water resistant for daily splashes",
      "Gift-ready brand packaging",
    ],
    specs: {
      Movement: "Quartz",
      Strap: "Stainless steel",
      WaterResistance: "50m",
      Warranty: "2 year Titan manufacturer warranty",
    },
  },
  {
    id: "prod-nike-tempo-next",
    title: "Woodland Casual Leather Outdoor Boots",
    brand: "Woodland",
    category: "Fashion",
    price: 4195,
    originalPrice: 5995,
    discountPercent: 30,
    rating: 4.4,
    reviewCount: 620,
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=900&auto=format&fit=crop&q=80",
    stock: 15,
    description: "Rugged nubuck leather boots built for durability, traction, and ankle support across city streets and outdoor trails.",
    features: [
      "Genuine durable nubuck leather",
      "Deep-grooved rubber lug outsole for grip",
      "Cushioned collar for ankle protection",
      "Heavy duty brass eyelets and reinforced laces",
    ],
    specs: {
      Material: "Genuine leather",
      Sole: "Thermo-polymer rubber",
      Warranty: "90 day manufacturer warranty",
    },
  },
  {
    id: "prod-skincare-serum",
    title: "Minimalist 10% Niacinamide Face Serum (30ml)",
    brand: "Minimalist",
    category: "Beauty & Personal Care",
    price: 599,
    originalPrice: 699,
    discountPercent: 14,
    rating: 4.6,
    reviewCount: 2310,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&auto=format&fit=crop&q=80",
    stock: 40,
    isTrending: true,
    description: "Nourishing daily serum formulated with pure Niacinamide and Zinc PCA to reduce blemishes, control excess sebum, and improve skin texture.",
    features: [
      "10% Niacinamide + 1% Zinc PCA formula",
      "Fragrance-free, essential oil-free, non-comedogenic",
      "Soothes redness and strengthens skin moisture barrier",
      "Dermatologically tested for all skin types",
    ],
    specs: {
      Volume: "30 ml",
      SkinType: "All skin types",
      Origin: "India",
    },
  },
  {
    id: "prod-coffee-beans",
    title: "Tata Tea Gold Premium Long Leaf Assam Black Tea (1kg)",
    brand: "Tata Tea",
    category: "Grocery & Essentials",
    price: 549,
    originalPrice: 660,
    discountPercent: 17,
    rating: 4.5,
    reviewCount: 1560,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=900&auto=format&fit=crop&q=80",
    stock: 60,
    description: "Exquisite blend of rich Assam CTC tea gently pressed with gently rolled aromatic long tea leaves for irresistible aroma and strong taste.",
    features: [
      "Rich aroma with 15% gently rolled long leaves",
      "Authentic blend sourced from premium Assam tea gardens",
      "Airtight hygienic packaging ensuring long freshness",
    ],
    specs: {
      Weight: "1 kg",
      Form: "Loose tea",
      ShelfLife: "12 months",
    },
  },
];
